---
- hosts: kubernetes-all
  become: true
  tasks:
    - name: Backup default k8s configutation on all nodes, provide all default files the .orig extension
      shell: 'if [ `ls -1 /etc/kubernetes/*.orig 2>/dev/null | wc -l` != 0 ] ; then echo "no backup taken, backup exsists"; else `for i in $(find /etc/kubernetes/ -type f ! -name "*.*"); do cp $i{,.orig}; done` ; fi'
      register: backup_k8s_default
    - name: get version output
      debug: var=backup_k8s_default.stdout_lines

    - name: Backup default etcd configutation on all nodes, provide all default files the .orig extension
      shell: 'if [ `ls -1 /etc/etcd/*.orig 2>/dev/null | wc -l` != 0 ] ; then echo "no backup taken, backup exsists"; else `for i in $(find /etc/etcd/ -type f ! -name "*."); do cp $i{,.orig} ; done` ; fi'
      register: backup_etcd_default
    - name: get version output
      debug: var=backup_etcd_default.stdout_lines

    - name: Disable SELinux on all nodes
      selinux:
        state: disabled

- hosts: kubernetes-masters
  become: true
  tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full | version_compare('2.3', '<')"
        msg: >
          "To use the playbook on Ansible >= 2.3, you must change the 'lineinfile' property 'dest' to path "

    # TODO remove port 4001
    - name: Let etcd listen on ports 2379 and 4001
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_LISTEN_CLIENT_URLS='
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"'
        #line: 'ETCD_LISTEN_CLIENT_URLS="http://{{ ansible_host }}:2379,http://{{ ansible_host }}:4001"'

    # TODO remove port 4001
    - name: Configure ETCD_ADVERTISE_CLIENT_URLS
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^.?ETCD_ADVERTISE_CLIENT_URLS='
        line: 'ETCD_ADVERTISE_CLIENT_URLS="http://localhost:2379,http://localhost:4001"'

#    - name: Enabled etcd debugging
#      lineinfile:
#        dest: "/etc/etcd/etcd.conf"
#        regexp: '^ETCD_DEBUG='
#        line: 'ETCD_DEBUG="true"'
#
#    - name: Set debugging levels
#      lineinfile:
#        dest: "/etc/etcd/etcd.conf"
#        regexp: '^ETCD_LOG_PACKAGE_LEVELS='
#        line: 'ETCD_LOG_PACKAGE_LEVELS="etcdmain=DEBUG,etcdserver=DEBUG,security=DEBUG"'

    - name: Enable and start etcd
      systemd:
        name: etcd
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Wait for port 2379
      wait_for:
        port: 2379