---
- hosts: kubernetes-all
  become: true
  tasks:
    - name: Backup default configutation on all nodes, copy all  .orig files
      shell: 'for i in $(find /etc/kubernetes/ -type f ! -name "*.*"); do cp $i{,.orig}; done'

    - name: Disable SELinux on all nodes
      selinux:
        state: disabled

- hosts: kubernetes-masters
  become: true
  tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full | version_compare('2.3', '<')"
        msg: >
          "To use the playbook on Ansible >= 2.3, you must change the 'lineinfile' property 'dest' to path "

    # TODO remove port 4001
    - name: Let etcd listen on ports 2379 and 4001
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_LISTEN_CLIENT_URLS='
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"'

    # TODO remove port 4001
    - name: Configure ETCD_ADVERTISE_CLIENT_URLS - only used for multi-instance etcd setups
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^.?ETCD_ADVERTISE_CLIENT_URLS='
        #line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"'
        line: 'ETCD_ADVERTISE_CLIENT_URLS="http://{{ ansible_host }}:2379,http://{{ ansible_host }}:4001"'

    - name: Enabled etcd debugging
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_DEBUG='
        line: 'ETCD_DEBUG="true"'

    - name: Set debugging levels
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_LOG_PACKAGE_LEVELS='
        line: 'ETCD_LOG_PACKAGE_LEVELS="etcdmain=DEBUG,etcdserver=DEBUG,security=DEBUG"'

    - name: Enable and start etcd
      systemd:
        name: etcd
        enabled: yes
        state: restarted
        #daemon_reload: yes

    - name: Wait for port 2379
      wait_for:
        port: 2379