---
# This playbook only adds the flannel configuration to the etcd server
- hosts: kubernetes-masters
  become_user: vagrant
  tasks:
    - name: Copy flannel configuration json
      copy:
        src: "{{ playbook_dir }}/resource/flannel-config-udp.json"
        dest: '~/flannel-config-udp.json'

    - name: Configure flannel
      shell: 'etcdctl set /atomic.io/network/config < ~/flannel-config-udp.json'

    - name: Test the change
      uri:
        url: "http://{{ etcd_server }}:2379/v2/keys{{ etcd_prefix }}/config"
        status_code: 200
        return_content: yes
      register: test_flannel
      #Check that
      until:  '"Network" in test_flannel.content'