---
- hosts: kubernetes-all
  become: true
  tasks:
    - name: Verify Ansible version
      assert:
        that: "ansible_version.full | version_compare('2.3', '<')"
        msg: >
          "To use the playbook on Ansible >= 2.3, you must change the 'lineinfile' property 'dest' to path "

    # Before installing flannel, be sure you have the etcd endpoint. Flannel needs etcd as its datastore. If Docker is running, stop the Docker service first and delete docker0
    - name: Stop docker
      systemd:
        name: docker
        enabled: yes
        state: stopped

    - name: Prepare for flannel, delete the default virtual bridge del docker0
      command: 'ip link del docker0'
      ignore_errors: yes

    - name: Set FLANNEL_ETCD
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^FLANNEL_ETCD='
        line: 'FLANNEL_ETCD="http://{{ master_ip }}:2379"'

    # Configure flannel daemon
    - name: Set FLANNEL_ETCD_KEY config key. This is the configuration key that flannel queriesFor address range assignment
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^FLANNEL_ETCD_KEY='
        line: 'FLANNEL_ETCD_KEY="{{ etcd_prefix }}"'

    - name: Set FLANNEL_ETCD_PREFIX
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^FLANNEL_ETCD_PREFIX='
        line: 'FLANNEL_ETCD_PREFIX="{{ etcd_prefix }}"'

    - name: Set FLANNEL_ETCD_PREFIX
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^#?FLANNEL_OPTIONS='
        line: 'FLANNEL_OPTIONS="-iface={{ kubernetes_nic_name }} -ip-masq=true"'

#    - name: Copy locked /usr/lib/systemd/system/flanneld.service to unlocked /etc/systemd/system/flanneld.service
#      copy:
#        remote_src: true #copy from the target machine
#        src: /usr/lib/systemd/system/flanneld.service
#        dest: /etc/systemd/system/flanneld.service

#    - name: Configure flannel ExecStart
#      lineinfile:
#        dest: "/etc/systemd/system/flanneld.service"
#        regexp: '^ExecStart='
#        line: "ExecStart=/usr/bin/flanneld -etcd-endpoints=http://{{ master_ip }}:2379 -etcd-prefix={{ etcd_prefix }} --iface={{ tmp_ip }}"
#        vars:
#          tmp_ip: ansible_{{ kubernetes_nic_name }}.ipv4.address

    - name: Reload flannel
      systemd:
        name: flanneld
        enabled: yes
        state: restarted
        daemon_reload: yes

### Restart server
#    - name: Restart server
#      shell: sleep 2 && systemctl reboot
#      async: 1
#      poll: 0
#      ignore_errors: true
#
#    - name: waiting for server to come back after reboot
#      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15


