---
- hosts: kubernetes-all
  become: true
  tasks:


    - name: Change default options
      # Somehoew this https://github.com/coreos/flannel#docker-integration is not nessesary. The flannel configuration
      # is picked up by docker
      lineinfile:
        dest: "/etc/sysconfig/docker"
        regexp: '^OPTIONS='
        #line: "OPTIONS='--log-driver=journald --bip 172.29.0.1/16'"
        #line: "OPTIONS='--log-driver=journald --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}'"
        line: "OPTIONS='--log-driver=journald'"

#    - name: Allow insecure
#      lineinfile:
#        dest: "/etc/sysconfig/docker"
#        regexp: '^INSECURE_REGISTRY='
#        line: "INSECURE_REGISTRY='--insecure-registry'"


#    - name: rm -fr /var/lib/docker/network/*
#      command: 'rm -fr /var/lib/docker/network/*'

    - name: Delete old docker network config files
      file:
        state: absent
        path: "/var/lib/docker/network/"


    - name: Reload docker
      systemd:
        name: docker
        enabled: yes
        state: restarted
        # reload isn't supported
