---
- hosts: kubernetes-kubelets
  become: true
  tasks:
    # TODO test this
    - name: Configure KUBELET_ADDRESS
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_ADDRESS='
        line: 'KUBELET_ADDRESS="--address={{ kubernetes_host_ip }}"'

    - name: Configure KUBELET_HOSTNAME
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_HOSTNAME='
        #line: 'KUBELET_HOSTNAME="--hostname-override={{ kubernetes_host_ip }}"'
        line: 'KUBELET_HOSTNAME="--hostname-override={{ inventory_hostname }}"'

    - name: Configure KUBELET_API_SERVER - location of the api-server
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_API_SERVER='
        line: 'KUBELET_API_SERVER="--api-servers=http://{{ master_ip }}:8080"'

    - name: Configure KUBELET_ARGS - add your own arguments
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^#?KUBELET_ARGS='
        #line: 'KUBELET_ARGS="--auth_path=/var/lib/kubelet/auth"'
        line: 'KUBELET_ARGS=""'

    - name: Configure KUBE_PROXY_ARGS - set --cluster-cidr on kube-proxy
      lineinfile:
        dest: "/etc/kubernetes/proxy"
        regexp: '^#?KUBE_PROXY_ARGS='
        #line: 'KUBELET_ARGS="--auth_path=/var/lib/kubelet/auth"'
        line: 'KUBE_PROXY_ARGS="--cluster-cidr=172.28.0.0/16"'


    - name: Reload kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Reload kube-proxy
      systemd:
        name: kube-proxy
        enabled: yes
        state: restarted
        daemon_reload: yes