---
- hosts: kubernetes-kubelets
  become: true
  tasks:
    # https://kubernetes.io/docs/admin/kubelet/

    # TODO test this
    - name: Due to a bug in kubernetes we must configure an empty JSON authorization file on each node.
      command: echo "{}" > /var/lib/kubelet/auth

    # TODO test this
    - name: Configure KUBELET_ADDRESS - The address for the info server to serve on
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_ADDRESS='
        line: 'KUBELET_ADDRESS="--address={{ kubernetes_host_ip }}"'

    - name: Configure KUBELET_HOSTNAME
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_HOSTNAME='
        line: 'KUBELET_HOSTNAME="--hostname_override={{ kubernetes_host_ip }}"'
        #line: 'KUBELET_HOSTNAME="--hostname_override={{ inventory_hostname }}"'


    - name: Configure location of the api-server
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_API_SERVER='
        line: 'KUBELET_API_SERVER="--api_servers=http://{{ master_ip }}:8080"'

    - name: Configure KUBELET_ARGS - add your own arguments
      lineinfile:
        dest: "/etc/kubernetes/kubelet"
        regexp: '^KUBELET_ARGS='
        line: 'KUBELET_ARGS=\"--auth_path=/var/lib/kubelet/auth\"'


    - name: Reload kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Reload kube-proxy
      systemd:
        name: kube-proxy
        enabled: yes
        state: restarted
        daemon_reload: yes