---
- hosts: kubernetes-kubelets
  become: true
  become_user: root
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address

    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full | version_compare('2.3', '<')"
        msg: >
          "To use the playbook on Ansible >= 2.3, you must change the 'lineinfile' property 'dest' to path "

    # TODO fix hardcoded ip
    - name: Configuring Docker to use the cluster registry cache
      lineinfile:
        dest: "/etc/sysconfig/docker"
        regexp: '^OPTIONS='
        line: "OPTIONS='--registry-mirror=http://192.168.56.10:5000 --selinux-enabled --log-driver=journald'"

    # TODO fix hardcoded ip
    - name: Configuring Docker to use the Flannel overlay 1
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^FLANNEL_ETCD_ENDPOINTS='
        line: 'FLANNEL_ETCD_ENDPOINTS="http://192.168.56.10:2379"'

    - name: Configuring Docker to use the Flannel overlay 2
      lineinfile:
        dest: "/etc/sysconfig/flanneld"
        regexp: '^FLANNEL_ETCD_PREFIX='
        line: 'FLANNEL_ETCD_PREFIX="/atomic.io/network"'

