---
- hosts: all
  become: true
  become_user: root
  tasks:
    # http://unix.stackexchange.com/questions/252684/why-am-i-getting-cannot-connect-to-the-docker-daemon-when-the-daemon-is-runnin
    - name: Allow the vagrant user to connect to docker
      # Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      user:
        name: vagrant
        groups: docker
        append: yes