---
- hosts: master
  become: true
  become_user: root
  tasks:
    - name: Verify Ansible version.
      assert:
        that: "ansible_version.full | version_compare('2.3', '<')"
        msg: >
          "To use the playbook on Ansible >= 2.3, you must change the 'lineinfile' property 'dest' to path "

    - name: Let etcd listen on ports 2379 and 4001
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_LISTEN_CLIENT_URLS='
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"'

    - name: Advertise that etcd listens on ports 2379 and 4001
      lineinfile:
        dest: "/etc/etcd/etcd.conf"
        regexp: '^ETCD_ADVERTISE_CLIENT_URLS='
        line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"'