---
- hosts: kubernetes-masters
  become: true
  strategy: debug
  gather_facts: yes
  # TODO make this file idempotent
  tasks:
    - name: Show username running the deploy
      local_action: command whoami
      register: username_on_the_host
    - debug: var=username_on_the_host

    - name: Create easy-rsa tmp folder
      file:
        path: /tmp/ansible/
        state: absent

    - name: Create easy-rsa tmp folder
      file:
        path: /tmp/ansible/
        state: directory

    - name: Download and extract easy-rsa
      unarchive:
        src: https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz
        dest: /tmp/ansible/
        remote_src: true

    - name: Init easy-rsa
      command: './easyrsa init-pki'
      args:
        chdir: /tmp/ansible/easy-rsa-master/easyrsa3

    - name: Generate cert 1
      command: './easyrsa --batch "--req-cn=`hostname`@`date +%s`" build-ca nopass'
      args:
        chdir: /tmp/ansible/easy-rsa-master/easyrsa3

    # TODO fix hardcoded IP-address
    - name: Generate cert 2
      command: './easyrsa --subject-alt-name="IP:192.168.56.10" build-server-full server nopass'
      args:
        chdir: /tmp/ansible/easy-rsa-master/easyrsa3

    - name: Create Kubernetes ./cert folder
      file:
        path: /etc/kubernetes/certs
        state: directory

    - name: Create Kubernetes ./certs/issued cert folder
      file:
        path: /etc/kubernetes/certs/issued
        state: directory

    - name: Create Kubernetes ./certs/private folder
      file:
        path: /etc/kubernetes/certs/private
        state: directory

    - name: Copy PKI files to Kubernetes cert folder
      copy:
        src: /tmp/ansible/easy-rsa-master/easyrsa3/pki/ca.crt
        dest: /etc/kubernetes/certs/ca.crt
      #copy:
      #  src: /tmp/ansible/easy-rsa-master/easyrsa3/pki/issued/server.crt
      #  dest: /etc/kubernetes/certs/issued/server.crt
      #  directory_mode: true

      #copy:
      #  src: /tmp/ansible/easy-rsa-master/easyrsa3/pki/private/server.key
      #  dest: /etc/kubernetes/certs/private/server.key


    - name: Change owner of the cert folder and files
      file:
        path: /etc/kubernetes/certs
        state: directory
        owner: kube
        group: kube









