---
- hosts: master
  become: true
  become_user: root
  tasks:
    - name: Configure flannel
      uri:
        #url: "{{ etcd_server }}/v2/keys/atomic.io/network/config"
        url: "http://localhost:2379/v2/keys/atomic.io/network/config"
        method: PUT
        body: |-
          value={
          'Network': '172.16.0.0/12,
          'SubnetLen': 24,
          'Backend: {
            'Type': 'vxlan'
             }
          }
        status_code: 200
        return_content: yes
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body_format: json

    - name: Test the change
      uri:
        url: "http://localhost:2379/v2/keys/atomic.io/network/config"
        status_code: 200
        return_content: yes
      register: test_flannel
      #Check that
      until:  '"Network" in test_flannel.content'
      retries: 5
      delay: 2
      ignore_errors: yes