---
- hosts: all
  become: false
  become_user: root
  tasks:
    - name: get versions before
      shell: cat /etc/os-release | grep ^VERSION=
      register: cat
      changed_when: false # this is a non mutating operation
    - name: get version output
      debug: var=cat.stdout_lines

    - name: deploy a specific version that supports infiniband
      # Current versions - 7.20161006 7.20170209 - replace on the line to suit your needs.
      shell: sleep 2 && atomic host deploy 7.20161006 -r
      #register: atomicout
      become: true
      # fire and forget - http://docs.ansible.com/ansible/playbooks_async.html
      async: 1
      poll: 0

    - name: waiting for server to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

    # http://docs.ansible.com/ansible/playbooks_error_handling.html#id6
    - name: reactivate all hosts
      meta: clear_host_errors

    # Print os version from the file /etc/os-release
    - name: get versions after
      shell: cat /etc/os-release | grep ^VERSION=
      register: cat
      changed_when: false
    - name: get version output
      debug: var=cat.stdout_lines
