---
- hosts: all
  become: false
  become_user: root
  tasks:
    - name: get version
      shell: cat /etc/os-release | grep ^VERSION=
      register: cat
      changed_when: false
    - name: get version output
      debug: var=cat.stdout_lines

    # Force upgrade/dowgrade atomic to a specific version.
    - name: upgrade/downgrade the atomic os to a specific version (atomic host upgrade) that supports infiniband
      # Current versions - 7.20161006 7.20170209 - replace on the line to suit your needs.
      shell: sleep 2 && atomic host deploy 7.20161006
      register: atomicout
      become: true

    # http://superuser.com/questions/1106349/cant-make-ansible-to-wait-for-a-server-to-reboot-and-continue-playbook-to-work
    - name: restart machine
      command: sleep 2 && systemctl reboot
      become: true
      async: 1
      poll: 0 #poll 0 = fire and forget - http://docs.ansible.com/ansible/playbooks_async.html
      ignore_errors: true

    - name: waiting for server to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15

    # http://docs.ansible.com/ansible/playbooks_error_handling.html#id6
    - name: reactivate all hosts
      meta: clear_host_errors

    - name: get version
      shell: cat /etc/os-release | grep ^VERSION=
      register: cat
      changed_when: false
    - name: get version output
      debug: var=cat.stdout_lines



#    - name: waiting for server to come back (might take a while)
#      local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=0 timeout=90
#
#    - name: get version
#      shell: cat /etc/os-release | grep ^VERSION=
#      register: cat
#    - name: get version output
#      debug: var=cat.stdout_lines